@startuml

class Administrator {
    - id: int
    - email: text
    - password: text
}

class Station {
    - id: int
    - stationName: String
}

class QueueManager {
    - id: number
    - admin: Administrator
    - queue: Queue
}

class Queue {
    - id: int
    - name: text
    - station: Station
}

class WaitingPosition {
    - id: int
    - visitor: Visitor
    - queue: Queue
}

class Visitor {
    - id: int
    - joinTime: text
}

Administrator "*" - "*" Queue : > manages
(Administrator, Queue) .. QueueManager
Station "1" -- "*" Queue : > has
Queue "*" - "*" Visitor : > stores
(Queue, Visitor) .. WaitingPosition

@enduml