### Get all visitors
GET http://localhost:3000/api/visitor

### Get visitor by id
GET http://localhost:3000/api/visitor/1

### Add visitor
POST http://localhost:3000/api/visitor
Content-Type: application/json

{
  "id": 4,
  "joinTime": "2024-05-03 12:02:46"
}

### Add QueueManager
POST http://localhost:3000/api/visitor/queues/2/visitor/444
Content-Type: application/json

{
  "id": 7,
  "joinTime": "2024-05-03 12:02:46"
}

### Delete Visitor from Queue
DELETE http://localhost:3000/api/visitor/queues/1/visitor/2